# Use the latest LTS version of Node.js
FROM node:20-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY package*.json ./
RUN npm ci # Odporúčané pre produkčné buildy
 
# Install dependencies
RUN npm install
 
# Copy the rest of your application files

 
# Expose the port your app runs on
EXPOSE 4173
 
# Define the command to run your app
CMD ["npm", "run", "preview"]